/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/skyscraper.glb 
*/

import gsap from "gsap";

import React, { useLayoutEffect, useRef } from "react";
import { useGLTF, useScroll } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export const FLOOR_HEIGHT = 2.3;
export const NB_FLOORS = 3;

export function Skyscraper(props) {
  const { nodes, materials } = useGLTF("./models/skyscraper.glb");
  const ref = useRef();
  const tl = useRef();

  const floor2 = useRef();
  const floor3 = useRef();

  const scroll = useScroll();

  useFrame(() => {
    tl.current.seek(scroll.offset * tl.current.duration());
  });

  useLayoutEffect(() => {
    tl.current = gsap.timeline();

    // Vertical Animation
    tl.current.to(
      ref.current.position,
      {
        duration: 2,
        y: -FLOOR_HEIGHT * (NB_FLOORS - 1),
      },
      0,
    );

    // Floor2 Animation
    // tl.current.from(
    //   floor2.current.position,
    //   {
    //     duration: 0.5,
    //     x: -2,
    //   },
    //   0.5,
    // );

    // Floor3 Animation
    // tl.current.from(
    //   floor3.current.position,
    //   {
    //     duration: 0.5,
    //     y: 2,
    //   },
    //   0.5,
    // );
  }, []);

  return (
    <group {...props} dispose={null} ref={ref}>
      <mesh
        geometry={nodes.Cylinder.geometry}
        material={nodes.Cylinder.material}
      />

      {/* <group position={[0, 10, 0]}>
        <ground ref={floor3} />
        <mesh
          geometry={nodes.Cylinder.geometry}
          material={nodes.Cylinder.material}
        />
      </group> */}
    </group>
  );
}

useGLTF.preload("./models/skyscraper.glb");
